FROM python:3.11-alpine

LABEL Name=sender Version=0.0.1

RUN apk update && apk add git

ADD /sender_requirements.txt /

RUN pip install -r sender_requirements.txt --no-cache

ADD /.env /

ADD /yandex_logging.py /clients.py /settings.py /sender.py /supabase_logs.py /

ADD clients.yaml /

EXPOSE 5000:8080

ENV FLASK_APP=sender.py

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]
