FROM python:3-slim

LABEL Name=sender Version=0.0.1

# RUN pip install -U --no-cache wheel setuptools pip

ADD /tg /tg
ADD /sender_requirements.txt /

# WORKDIR /src

RUN pip install -r sender_requirements.txt --no-cache

ADD /.env /
ADD /settings.py /
ADD /sender.py /

EXPOSE 5000:8080

ENV FLASK_APP=sender.py

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]
